name: use my action
on: workflow_dispatch

jobs:
  my_job:
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v1
     - name: My first step
       uses: ./.github/actions/cancel-if-unchanged